name: Simulação de Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  simulate:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Executar deploy simulado
      run: |
        python main.py
