name: Builds (APK)

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.2
  FLUTTER_VERSION: 3.22.2

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet flet-core

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Accept Android Licenses
      run: yes | flutter doctor --android-licenses

    - name: Run Flutter Doctor
      run: flutter doctor -v

    - name: Prepara build do app
      run: |
        flet clean
        flet build init --template gh:flet-dev/flet-build-template@0.28.3
        flet build app

    - name: Verifica arquivos empacotados
      run: |
        echo "Arquivos empacotados:"
        ls -R build/flet/app

    - name: Build APK
      run: |
        flet build apk --verbose \
          --build-number=${{ env.BUILD_NUMBER }} \
          --build-version=${{ env.BUILD_VERSION }}

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk-build-artifact
        path: "**/*.apk"
